{"version":3,"sources":["../../server/middlewares/exception.js"],"names":["ctx","next","body","error","message","str","method","url"],"mappings":"uSAAA,yC;;AAEe,mBAAgBA,GAAhB,EAAqBC,IAArB;;AAELA,oBAFK;;AAIXD,gBAAIE,IAAJ,GAAW;AACTC,qBAAO,YAAEC,OADA,EAAX;;;AAIMC,eARK,GAQIL,IAAIM,MARR,SAQkBN,IAAIO,GARtB,WAQ+B,YAAEH,OARjC;AASX,+BAAMC,GAAN,EATW,yE","file":"exception.js","sourcesContent":["import { error } from '../utils/logger'\n\nexport default async function (ctx, next) {\n  try {\n    await next()\n  } catch (e) {\n    ctx.body = {\n      error: e.message,\n    }\n\n    const str = `${ctx.method} ${ctx.url} - ${e.message}`\n    error(str)\n  }\n}\n"]}